export default {
    discover: require("../assets/icons/compass.png"),
    search: require("../assets/icons/search.png"),
    library: require("../assets/icons/library-big.png"),
    account: require("../assets/icons/circle-user-round.png"),
    leftArrow: require("../assets/icons/left-arrow.png"),
    menu: require("../assets/icons/menu.png"),
    upload: require("../assets/icons/upload.png"),
    rightArrow: require("../assets/icons/right-arrow.png"),
    logout: require("../assets/icons/logout.png"),
    eyeHide: require("../assets/icons/eye-hide.png"),
    eye: require("../assets/icons/eye.png"),
    play: require("../assets/icons/play.png"),
    paused: require("../assets/icons/pause.png"),
    plus: require("../assets/icons/plus.png"),
    camera: require("../assets/icons/camera.png"),
    arrowDown: require("../assets/icons/arrow-down.png"),
    back: require("../assets/icons/back.png"),
    heart: require("../assets/icons/heart.png"),
    heartFill: require("../assets/icons/heart-fill.png"),
    download: require("../assets/icons/download.png"),
    shuffle: require("../assets/icons/shuffle.png"),
    share: require("../assets/icons/share.png"),
    setting: require("../assets/icons/settings.png"),
}